# Bring up the server:
#
#   docker-compose up server-sw
#
# Run the tests:
#
#   docker-compose run test-sw
#
# For HW mode, replace `sw` with `hw`.

services:

  server-sw:
    profiles: ["sw"]
    build:
      context: .
      args:
        SGX_MODE: "SW"
      target: run-trusted-contract-execution-enclave-server-sw
    read_only: false
    init: true
    environment:
      BIND_ADDR: "0.0.0.0:8000"
    volumes:
       - wallet-data-sw:/app/wallet_store
    ports:
      - "8000:8000"

  server-hw:
    profiles: ["hw"]
    build:
      context: .
      args:
        SGX_MODE: "HW"
      target: run-trusted-contract-execution-enclave-server-hw
    read_only: false
    init: true
    environment:
      BIND_ADDR: "0.0.0.0:8000"
    devices:
      - /dev/sgx/enclave
      - /dev/sgx/provision
    volumes:
       - wallet-data-hw:/app/wallet_store
    ports:
      - "8000:8000"

volumes:
  wallet-data-sw:
  wallet-data-hw:
