[package]
name = "wasmi-impl"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmi = { version = "0.11.0", default-features = false }

[dev-dependencies]
wabt = "0.10.0"
