[package]
name = "get-median-wasm"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ['cdylib']

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.release]
lto = true
opt-level = 's'
