name: "execution-enclave-server (SW)"

on: push

# New pushes cancel in-progress builds.
concurrency:
  group: ${{ github.workflow }} - ${{ github.job }} - ${{ github.ref }}
  cancel-in-progress: true

# Action docs:
#
# - https://github.com/docker/build-push-action#readme
# - https://github.com/docker/login-action#readme
# - https://github.com/docker/metadata-action#readme
# - https://github.com/docker/setup-buildx-action#readme
#
# For the context paths, see:
#
# - Feature request: Allow specifying subdirectory with default git context #460
#   https://github.com/docker/build-push-action/issues/460

jobs:

  build-stage-execution-enclave-server-builder:
    name: "Builder"
    runs-on: ubuntu-latest
    steps:
      -
        uses: docker/setup-buildx-action@v1
      -
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: "Build stage: execution-enclave-server-builder"
        uses: docker/build-push-action@v2
        with:
          context: "https://github.com/${{ github.repository }}.git#${{ github.sha }}"
          target: web-server-builder
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:buildcache-sw
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}:buildcache-sw,mode=max

  build-stage-run-trusted-contract-execution-enclave-server-sw:
    name: "Build server (SW)"
    runs-on: ubuntu-latest
    needs: build-stage-execution-enclave-server-builder
    steps:
      -
        uses: docker/setup-buildx-action@v1
      -
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository_owner }}/trusted-contract-execution-enclave-sw
      -
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: "Build stage: run-trusted-contract-execution-enclave-server-sw"
        uses: docker/build-push-action@v2
        with:
          context: "https://github.com/${{ github.repository }}.git#${{ github.sha }}"
          build-args: 'SGX_MODE=SW'
          secrets: |
            "sgx-signing-key=${{ secrets.SGX_SIGNING_KEY }}"
          target: run-trusted-contract-execution-enclave-server-sw
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:buildcache-sw
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}:buildcache-sw,mode=max


